env:
  browser: true
  es6: true
  node: true
  webextensions: true

extends:
  - eslint:recommended

root: true

rules:
  eqeqeq: error
  indent: [warn, 2]
  no-console: warn
  no-var: warn
  prefer-const: warn
  quotes: [error, single]
